# frozen_string_literal: true

require 'seriamp/yamaha/parser/status_response_parser'
require 'spec_helper'

describe Seriamp::Yamaha::Parser::StatusResponseParser do
  describe '.parse' do
    let(:parsed) { described_class.parse(status_response) }

    context 'RX-V1500' do

      let(:status_middle) do
        -'@E01900021000517A7734132400011023000000002301100292426262620202828320000001414000000140051000000202401100002429262626202028283251770000701'
      end

      let(:status_response) do
        "R0177F8A#{status_middle}04"
      end

      let(:expected) do
        {
          firmware_version:'F',
          model_code:'R0177',
          model_name:'RX-V1500/HTR-5890',
          :busy=>false,
          :main_power=>true,
          :zone2_power=>false,
          :zone3_power=>false,
          :input_name=>"CD",
          :multi_ch_input=>false,
          :input_mode=>"Auto",
          :main_mute=>false,
          :zone2_input_name=>"DVD",
          :zone2_mute=>true,
          :main_volume=>-38.5,
          :zone2_volume=>-40.0,
          :program_name=>"2ch Stereo",
          :effect=>true,
          :es_key=>"Auto",
          :osd_message=>"Full",
          :sleep=>30,
          :tuner_page=>"A",
          :tuner_number=>1,
          :night_mode=>"Off",
          :pure_direct=>true,
          :speaker_a=>true,
          :speaker_b=>false,
          :playback_mode=>"PCM",
          :sample_rate=>"48000",
          :es_status=>"Off",
          :thr_bypass=>false,
          :red_dts_wait=>false,
          :headphone=>false,
          :tuner_band=>"FM",
          :tuned=>false,
          :trigger1=>false,
          :trigger1_control=>"???",
          :dts_96_24=>false,
          :trigger2_control=>"Zone2",
          :trigger2=>true,
          :speaker_b_zone=>"Zone1",
          :zone2_speaker=>false,
          :main_right_level=>0.5,
          :main_left_level=>-2.0,
          :center_level=>-1.0,
          :surround_right_level=>-1.0,
          :surround_left_level=>-1.0,
          :surround_back_right_level=>-4.0,
          :surround_back_left_level=>-4.0,
          :front_effect_right_level=>0.0,
          :front_effect_left_level=>0.0,
          :subwoofer_level=>5.0,
          :night_mode_parameter=>"Low",
          :speaker_lfe_level=>-10.0,
          :headphone_lfe_level=>-10.0,
          :audio_delay=>0,
          :input_mode_setting=>"Last",
          :dimmer=>0,
          :osd_shift=>0,
          :gray_back=>true,
          :video_conversion=>false,
          :speaker_dynamic_range=>"Max",
          :headphone_dynamic_range=>"Max",
          :zone2_volume_out=>"Variable",
          :memory_guard=>false,
          :center_speaker_setting=>"None",
          :main_speaker_setting=>"Large",
          :surround_speaker_setting=>"None",
          :surround_back_speaker_setting=>"None",
          :front_effect_speaker_setting=>true,
          :bass_out=>"Front/Main",
          :multi_ch_center_out=>"Main",
          :multi_ch_subwoofer_out=>"Subwoofer",
          :main_level=>"Normal",
          :test_mode=>"Off",
          :multi_ch_main_left_level=>-2.0,
          :multi_ch_main_right_level=>0.5,
          :multi_ch_center_level=>-1.0,
          :multi_ch_surround_left_level=>-1.0,
          :multi_ch_surround_right_level=>-1.0,
          :multi_ch_surround_back_left_level=>-4.0,
          :multi_ch_surround_back_right_level=>-4.0,
          :multi_ch_front_effect_left_level=>0.0,
          :multi_ch_front_effect_right_level=>0.0,
          :multi_ch_subwoofer_level=>5.0,
          :zone3_input_name=>"DVD",
          :zone3_mute=>true,
          :zone3_volume=>-40.0,
          :multi_ch_select_1500=>"6ch",
          :multi_ch_surround_out=>"Surround",
          :subwoofer_position=>"L-R",
          :subwoofer_crossover=>160,
          :component_osd=>false,
          :presence_surround_back_select=>"Surround Back",
          :raw_string=>status_middle,
        }
      end

      it 'works' do
        parsed.state.should == expected
      end
    end

    context 'HTR-5890' do

      let(:status_middle) do
        -'@E019000240005198771713242701112200000010210110028282823253B282828280000001414000000141051100000200401200002828282523283B28282851770000211'
      end

      let(:status_response) do
        "R0177F8A#{status_middle}48"
      end

      let(:expected) do
        {
          :busy=>false,
          :main_power=>true,
          :zone2_power=>false,
          :zone3_power=>false,
          :input_name=>"MD/TAPE",
          :multi_ch_input=>false,
          :input_mode=>"Auto",
          :main_mute=>false,
          :zone2_input_name=>"DVD",
          :zone2_mute=>true,
          :main_volume=>-23.5,
          :zone2_volume=>-40.0,
          :program_name=>"7ch Stereo",
          :effect=>true,
          :es_key=>"Auto",
          :osd_message=>"Short",
          :sleep=>30,
          :tuner_page=>"C",
          :tuner_number=>8,
          :night_mode=>"Off",
          :pure_direct=>true,
          :speaker_a=>true,
          :speaker_b=>true,
          :playback_mode=>"PCM",
          :sample_rate=>"44100",
          :es_status=>"Off",
          :thr_bypass=>false,
          :red_dts_wait=>false,
          :headphone=>false,
          :tuner_band=>"FM",
          :tuned=>false,
          :trigger1=>true,
          :trigger1_control=>"Zone2",
          :dts_96_24=>false,
          :trigger2_control=>"Zone2",
          :trigger2=>true,
          :speaker_b_zone=>"Zone1",
          :zone2_speaker=>false,
          :main_right_level=>0.0,
          :main_left_level=>0.0,
          :center_level=>0.0,
          :surround_right_level=>-2.5,
          :surround_left_level=>-1.5,
          :surround_back_right_level=>9.5,
          :surround_back_left_level=>0.0,
          :front_effect_right_level=>0.0,
          :front_effect_left_level=>0.0,
          :subwoofer_level=>0.0,
          :night_mode_parameter=>"Low",
          :speaker_lfe_level=>-10.0,
          :headphone_lfe_level=>-10.0,
          :audio_delay=>0,
          :input_mode_setting=>"Last",
          :dimmer=>0,
          :osd_shift=>0,
          :gray_back=>true,
          :video_conversion=>true,
          :speaker_dynamic_range=>"Max",
          :headphone_dynamic_range=>"Max",
          :zone2_volume_out=>"Variable",
          :memory_guard=>false,
          :center_speaker_setting=>"None",
          :main_speaker_setting=>"Large",
          :surround_speaker_setting=>"Large",
          :surround_back_speaker_setting=>"None",
          :front_effect_speaker_setting=>true,
          :bass_out=>"Front/Main",
          # This is important.
          :multi_ch_center_out=>"???",
          :multi_ch_subwoofer_out=>"Subwoofer",
          :main_level=>"Normal",
          :test_mode=>"Off",
          :multi_ch_main_left_level=>0.0,
          :multi_ch_main_right_level=>0.0,
          :multi_ch_center_level=>0.0,
          :multi_ch_surround_left_level=>-1.5,
          :multi_ch_surround_right_level=>-2.5,
          :multi_ch_surround_back_left_level=>0.0,
          :multi_ch_surround_back_right_level=>9.5,
          :multi_ch_front_effect_left_level=>0.0,
          :multi_ch_front_effect_right_level=>0.0,
          :multi_ch_subwoofer_level=>0.0,
          :zone3_input_name=>"DVD",
          :zone3_mute=>true,
          :zone3_volume=>-40.0,
          :multi_ch_select_1500=>"6ch",
          :multi_ch_surround_out=>"Surround",
          :subwoofer_position=>"L-R",
          :subwoofer_crossover=>80,
          :component_osd=>true,
          :presence_surround_back_select=>"Surround Back",
          :model_code=>"R0177",
          :model_name=>"RX-V1500/HTR-5890",
          :firmware_version=>"F",
          :raw_string=>"@E019000240005198771713242701112200000010210110028282823253B282828280000001414000000141051100000200401200002828282523283B28282851770000211"
        }
      end

      it 'works' do
        parsed.state.should == expected
      end
    end

    context 'RX-V1700' do

      let(:status_middle) do
        -'@E019000201005091773403140000000109200F1020001002A262828282828282828000201141400FFA114005110000000000120001000000101002000000105077000121100A0A01FFFF01100006FF146FF14210A0A00'
      end

      let(:status_response) do
        "R0210IAE#{status_middle}FB"
      end

      let(:expected) do
        {
          :ready=>"OK",
          :main_power=>true,
          :zone2_power=>false,
          :zone3_power=>false,
          :input_name=>"CD",
          :audio_source=>"Auto",
          :main_mute=>false,
          :zone2_input_name=>"DVD",
          :zone2_mute=>false,
          :main_volume=>-27.0,
          :zone2_volume=>-40.0,
          :program_name=>"2ch Stereo",
          :es_key=>"Auto",
          :osd_message=>"Short",
          :sleep=>nil,
          :tuner_page=>"A",
          :tuner_number=>1,
          :night_mode=>"Off",
          :night_mode_parameter=>"Low",
          :audio_format=>"PCM",
          :sample_rate=>"48000",
          :channel_indicator=>"2/0",
          :headphone=>false,
          :tuner_band=>"FM",
          :lfe_indicator=>nil,
          :trigger1=>true,
          :decoder_mode=>"Auto",
          :dual_mono_out=>"All",
          :trigger1_control=>"All",
          :trigger2_control=>"All",
          :trigger2=>true,
          :zone2_speaker_out=>"Ext",
          :front_right_level=>1.0,
          :front_left_level=>-1.0,
          :center_level=>0.0,
          :surround_right_level=>0.0,
          :surround_left_level=>0.0,
          :surround_back_right_level=>0.0,
          :surround_back_left_level=>0.0,
          :presence_right_level=>0.0,
          :presence_left_level=>0.0,
          :subwoofer_level=>0.0,
          :xm_preset_page=>"A",
          :xm_preset_number=>1,
          :xm_search_mode=>"All",
          :on_screen=>"30",
          :xm_channel_number=>1,
          :speaker_lfe_level=>-10.0,
          :headphone_lfe_level=>-10.0,
          :audio_delay=>0,
          :decoder_mode_setting=>"Last",
          :program_select=>"Last",
          :dimmer=>0,
          :osd_shift=>0,
          :gray_back=>true,
          :video_conversion=>true,
          :speaker_dynamic_range=>"Max",
          :headphone_dynamic_range=>"Max",
          :zone2_volume_out=>"Variable",
          :zone3_volume_out=>"Variable",
          :memory_guard=>false,
          :center_speaker_setting=>"Large",
          :front_speaker_setting=>"Large",
          :surround_speaker_setting=>"Large",
          :surround_back_speaker_setting=>"Large x2",
          :zone3_speaker_out=>"Ext",
          :presence_speaker_setting=>false,
          :bass_out=>"Both",
          :subwoofer_phase=>"Normal",
          :test_mode=>false,
          :eq_select=>"GEQ",
          :hdmi_audio=>true,
          :component_ip=>false,
          :hdmi_ip=>true,
          :hdmi_upscaling=>"480p (576p)",
          :hdmi_aspect=>"Through",
          :decoder_select=>"Pro Logic",
          :tuner_remote_id=>"ID1",
          :advanced_setup=>false,
          :amp_remote_id=>"ID1",
          :speaker_impedance=>8,
          :tuner_setup=>"AM9/FM0",
          :pure_direct=>false,
          :zone3_input_name=>"DVD",
          :zone3_mute=>false,
          :zone3_volume=>-40.0,
          :remote_sensor=>false,
          :multi_ch_select=>"6ch",
          :remote_id_xm=>"ID1",
          :biamp=>false,
          :subwoofer_crossover=>80,
          :presence_surround_back_select=>"Surround Back",
          :zone2_bass=>0,
          :zone2_treble=>0,
          :tone_auto_bypass=>true,
          :wake_on_rs232=>true,
          :bit_rate=>nil,
          :dialog_level=>nil,
          :fl_scroll=>"Continue",
          :multi_ch_bgv=>"Last",
          :ipod_charge_standby=>true,
          :ipod_repeat=>"Off",
          :ipod_shuffle=>"Off",
          :zone2_balance=>0.0,
          :zone3_balance=>0.0,
          :monitor_check=>true,
          :zone3_bass=>0,
          :zone3_treble=>0,
          :dd_karaoke=>false,
          :dd_61=>false,
          :dts_es_matrix_61=>false,
          :dts_es_discrete_61=>false,
          :dts_96_24=>false,
          :pre_emphasis=>false,
          :dpl_encoded=>false,
          :model_code=>"R0210",
          :model_name=>"RX-V1700",
          :firmware_version=>"I",
          :raw_string=>status_middle,
        }
      end

      it 'works' do
        parsed.state.should == expected
      end
    end

    context 'RX-V2700' do

      let(:status_middle) do
        -'@E01900020430507B778003140500000108200F1020001002828262626262628282800020114140000A114055110000020240120001000000103002000000115077000121100A0A01FFFF0110000A0014A0014210A0A00'
      end

      let(:status_response) do
        "R0212IAE#{status_middle}A8"
      end

      let(:expected) do
        {
          firmware_version:'I',
          model_code:'R0212',
          model_name:'RX-V2700',
          :ready=>"OK",
          :main_power=>true,
          :zone2_power=>false,
          :zone3_power=>false,
          :input_name=>"MD/TAPE",
          :audio_source=>"Coax / Opt",
          :main_mute=>false,
          :zone2_input_name=>"DVD",
          :zone2_mute=>false,
          :main_volume=>-38.0,
          :zone2_volume=>-40.0,
          :program_name=>"Straight",
          :es_key=>"Auto",
          :osd_message=>'Short',
          :sleep=>nil,
          :tuner_page=>"A",
          :tuner_number=>6,
          :night_mode=>"Off",
          :night_mode_parameter=>"Low",
          :audio_format=>"PCM",
          :sample_rate=>"44100",
          :channel_indicator=>"2/0",
          :headphone=>false,
          :tuner_band=>"FM",
          :lfe_indicator=>nil,
          :trigger1=>true,
          :decoder_mode=>"Auto",
          :dual_mono_out=>"All",
          :trigger1_control=>"All",
          :trigger2_control=>"All",
          :trigger2=>true,
          :zone2_speaker_out=>"Ext",
          :front_right_level=>0.0,
          :front_left_level=>0.0,
          :center_level=>-1.0,
          :surround_right_level=>-1.0,
          :surround_left_level=>-1.0,
          :surround_back_right_level=>-1.0,
          :surround_back_left_level=>-1.0,
          :presence_right_level=>0.0,
          :presence_left_level=>0.0,
          :subwoofer_level=>0.0,
          :xm_preset_page=>"A",
          :xm_preset_number=>1,
          :xm_search_mode=>"All",
          :on_screen=>"30",
          :xm_channel_number=>1,
          :speaker_lfe_level=>-10.0,
          :headphone_lfe_level=>-10.0,
          :audio_delay=>0,
          :initial_volume=>nil,
          :max_volume=>16.5,
          :decoder_mode_setting=>"Last",
          :program_select=>"Last",
          :dimmer=>0,
          :gui_position_h=>0,
          :gui_position_v=>0,
          :gray_back=>true,
          :video_conversion=>true,
          :speaker_dynamic_range=>"Max",
          :headphone_dynamic_range=>"Max",
          :zone2_volume_out=>"Variable",
          :zone3_volume_out=>"Variable",
          :memory_guard=>false,
          :center_speaker_setting=>"None",
          :front_speaker_setting=>"Large",
          :surround_speaker_setting=>"None",
          :surround_back_speaker_setting=>"None",
          :zone3_speaker_out=>"Ext",
          :presence_speaker_setting=>false,
          :bass_out=>"Both",
          :subwoofer_phase=>"Normal",
          :test_mode=>false,
          :eq_select=>"GEQ",
          :wallpaper=>"Yes",
          :hdmi_audio=>true,
          :component_ip=>false,
          :hdmi_ip=>true,
          :gui_language=>"English",
          :hdmi_upscaling=>"720p",
          :hdmi_aspect=>"Through",
          :zone_osd=>"Zone2 & Zone3",
          :decoder_select=>"Pro Logic",
          :tuner_remote_id=>"ID1",
          :advanced_setup=>false,
          :amp_remote_id=>"ID1",
          :speaker_impedance=>8,
          :tuner_setup=>"AM9/FM0",
          :pure_direct=>true,
          :zone3_input_name=>"DVD",
          :zone3_mute=>false,
          :zone3_volume=>-40.0,
          :remote_sensor=>false,
          :multi_ch_select=>"6ch",
          :remote_id_xm=>"ID1",
          :biamp=>false,
          :subwoofer_crossover=>80,
          :tv_format=>"NTSC",
          :presence_surround_back_select=>"Surround Back",
          :zone2_bass=>0,
          :zone2_treble=>0,
          :tone_auto_bypass=>true,
          :wake_on_rs232=>true,
          :bit_rate=>nil,
          :dialog_level=>nil,
          :fl_scroll=>"Continue",
          :multi_ch_bgv=>"Last",
          :ipod_charge_standby=>true,
          :ipod_repeat=>"Off",
          :ipod_shuffle=>"Off",
          :net_usb_repeat=>"Off",
          :net_usb_shuffle=>false,
          :zone2_max_volume=>16.5,
          :zone2_initial_volume=>nil,
          :zone2_balance=>0.0,
          :zone3_max_volume=>16.5,
          :zone3_initial_volume=>nil,
          :zone3_balance=>0.0,
          :net_usb_source=>"USB",
          :monitor_check=>true,
          :zone3_bass=>0,
          :zone3_treble=>0,
          :dd_karaoke=>false,
          :dd_61=>false,
          :dts_es_matrix_61=>false,
          :dts_es_discrete_61=>false,
          :dts_96_24=>false,
          :pre_emphasis=>false,
          :dpl_encoded=>false,
          :raw_string=>status_middle,
        }
      end

      it 'works' do
        parsed.state.should == expected
      end

      context 'in standby' do
        let(:status_middle) do
          -'@E0190000'
        end

        let(:status_response) do
          "R0212I09#{status_middle}A8"
        end

        let(:expected) do
          {
            firmware_version:'I',
            model_code:'R0212',
            model_name:'RX-V2700',
            :ready=>"OK",
            :main_power=>false,
            :zone2_power=>false,
            :zone3_power=>false,
            :raw_string=>status_middle,
          }
        end

        it 'works' do
          parsed.state.should == expected
        end
      end
    end

    context 'RX-V1800' do

      let(:status_middle) do
        -'@E0190002040050B94D3403140300000108200F1020001002828282828282828282800030114140000A00400511000000000002000200000000000200000010504D00012100070E01FFFF0110000A0014A0014210A0A00FF10110'
      end

      let(:status_response) do
        "R0226JB5#{status_middle}1E"
      end

      let(:expected) do
        {
          firmware_version:'J',
          model_code:'R0226',
          model_name:'RX-V1800',
          :ready=>"OK",
          :main_power=>true,
          :zone2_power=>false,
          :zone3_power=>false,
          :input_name=>"MD/TAPE",
          :audio_source=>"Auto",
          :main_mute=>false,
          :zone2_input_name=>"DVD",
          :zone2_mute=>false,
          :main_volume=>-7.0,
          :zone2_volume=>-61.0,
          :program_name=>"2ch Stereo",
          :es_key=>"Auto",
          :osd_message=>'Short',
          :sleep=>nil,
          :tuner_page=>"A",
          :tuner_number=>4,
          :audio_format=>"PCM",
          :sample_rate=>"44100",
          :channel_indicator=>"2/0",
          :headphone=>false,
          :tuner_band=>"FM",
          :lfe_indicator=>nil,
          :trigger1=>true,
          :decoder_mode=>"Auto",
          :dual_mono_out=>"All",
          :trigger1_control=>"All",
          :trigger2_control=>"All",
          :trigger2=>true,
          :zone2_speaker_out=>"Ext",
          :front_right_level=>0.0,
          :front_left_level=>0.0,
          :center_level=>0.0,
          :surround_right_level=>0.0,
          :surround_left_level=>0.0,
          :surround_back_right_level=>0.0,
          :surround_back_left_level=>0.0,
          :presence_right_level=>0.0,
          :presence_left_level=>0.0,
          :subwoofer_level=>0.0,
          :xm_preset_page=>"A",
          :xm_preset_number=>1,
          :xm_search_mode=>"All",
          :on_screen=>"Always",
          :xm_channel_number=>1,
          :speaker_lfe_level=>-10.0,
          :headphone_lfe_level=>-10.0,
          :audio_delay=>0,
          :initial_volume=>nil,
          :max_volume=>16.5,
          :decoder_mode_setting=>"Auto",
          :program_select=>"Auto",
          :dimmer=>0,
          :osd_shift=>0,
          :gray_back=>true,
          :video_conversion=>true,
          :speaker_dynamic_range=>"Max",
          :headphone_dynamic_range=>"Max",
          :zone2_volume_out=>"Variable",
          :zone3_volume_out=>"Variable",
          :memory_guard=>false,
          :center_speaker_setting=>"Large",
          :front_speaker_setting=>"Large",
          :surround_speaker_setting=>"Large",
          :surround_back_speaker_setting=>"Large x2",
          :zone3_speaker_out=>"Ext",
          :presence_speaker_setting=>true,
          :bass_out=>"Both",
          :subwoofer_phase=>"Normal",
          :test_mode=>false,
          :eq_select=>"Off",
          :hdmi_audio=>true,
          :component_ip=>false,
          :hdmi_upscaling=>"Through",
          :hdmi_aspect=>"Through",
          :decoder_select=>"Pro Logic",
          :tuner_remote_id=>"ID1",
          :advanced_setup=>false,
          :amp_remote_id=>"ID1",
          :speaker_impedance=>8,
          :tuner_setup=>"AM9/FM0",
          :pure_direct=>false,
          :zone3_input_name=>"DVD",
          :zone3_mute=>false,
          :zone3_volume=>-61.0,
          :remote_sensor=>false,
          :multi_ch_select=>"6ch",
          :remote_id_xm=>"ID1",
          :biamp=>false,
          :subwoofer_crossover=>80,
          :tv_format=>"NTSC",
          :presence_surround_back_select=>"Presence",
          :zone2_bass=>-3,
          :zone2_treble=>4,
          :tone_auto_bypass=>true,
          :wake_on_rs232=>true,
          :bit_rate=>nil,
          :dialog_level=>nil,
          :fl_scroll=>"Continue",
          :multi_ch_bgv=>"Last",
          :ipod_charge_standby=>true,
          :ipod_repeat=>"Off",
          :ipod_shuffle=>"Off",
          :zone2_max_volume=>16.5,
          :zone2_initial_volume=>nil,
          :zone2_balance=>0.0,
          :zone3_max_volume=>16.5,
          :zone3_initial_volume=>nil,
          :zone3_balance=>0.0,
          :monitor_check=>true,
          :zone3_bass=>0,
          :zone3_treble=>0,
          :dd_karaoke=>false,
          :dd_61=>false,
          :dts_es_matrix_61=>false,
          :dts_es_discrete_61=>false,
          :dts_96_24=>false,
          :pre_emphasis=>false,
          :dpl_encoded=>false,
          _3d_dsp: false,
          adaptive_drc: 'Off',
          adaptive_dsp_level: 'Off',
          auto_audio_delay: '--',
          extended_surround_setting: 'Auto',
          hdmi_lip_sync: true,
          :raw_string=>status_middle,
        }
      end

      it 'works' do
        parsed.state.should == expected
      end
    end
  end
end
