# frozen_string_literal: true

require 'spec_helper'

describe Seriamp::Yamaha::Executor do
  let(:executor) { described_class.new(client) }

  describe '#build_fields' do
    let(:client) { double('test client') }
    let(:status_fields) { Seriamp::Yamaha::Protocol::GetConstants::STATUS_FIELDS }
    let(:model_id) { Seriamp::Yamaha::Client::MODEL_IDS.fetch(model_name) }

    context 'RX-V1700' do
      let(:model_name) { 'RX-V1700' }

      it 'returns correct fields' do
        executor.send(:build_fields, status_fields, model_id).should == [
          "Baud rate (@)",
          "Receive buffer (E)",
          "Receive buffer (0)",
          "Command timeout (1)",
          "Command timeout (9)",
          "Command timeout (0)",
          "Handshaking (0)",
          "System busy flag",
          "Power boolean",
          "Input",
          "Multi-channel input",
          "Input mode",
          "Mute",
          "Zone 2 input",
          "Zone 2 mute",
          "Master volume",
          "Master volume",
          "Zone 2 volume",
          "Zone 2 volume",
          "Program",
          "Program",
          "Effect",
          "Extended surround",
          "OSD short message",
          "Sleep timer",
          "Tuner preset page",
          "Tuner preset number",
          "Night mode",
          "Night mode parameter",
          "Speaker A relay",
          "Speaker B relay",
          "Format",
          "Format",
          "Sampling",
          "Sampling",
          "Channels front/rear",
          "Headphones",
          "Tuner band",
          "Channel LFE",
          "Trigger 1 output",
          "Decoder mode",
          "Dual mono",
          "Trigger 1 control",
          "N/A",
          "Trigger 2 control",
          "Trigger 2 output",
          "Speaker B setting",
          "Zone 2 amplifier",
          "Level front right",
          "Level front right",
          "Level front left",
          "Level front left",
          "Level center",
          "Level center",
          "Level surround right",
          "Level surround right",
          "Level surround left",
          "Level surround left",
          "Level surround back right",
          "Level surround back right",
          "Level surround back left",
          "Level surround back left",
          "Level presence right",
          "Level presence right",
          "Level presence left",
          "Level presence left",
          "Level subwoofer",
          "Level subwoofer",
          "XM preset page",
          "XM preset number",
          "XM search mode",
          "On screen OSD",
          "XM channel number",
          "XM channel number",
          "LFE level speakers",
          "LFE level speakers",
          "LFE level headphones",
          "LFE level headphones",
          "Audio delay",
          "Audio delay",
          "Initial volume",
          "Initial volume",
          "Max volume",
          "Decoder mode setting",
          "Audio select setting",
          "Dimmer",
          "N/A",
          "OSD shift",
          "OSD shift",
          "Gray back",
          "Video conversion",
          "Dynamic range speakers",
          "Dynamic range headphones",
          "Zone 2 volume out",
          "Zone 3 volume out",
          "Memory guard",
          "Speaker setting center",
          "Speaker setting front",
          "Speaker setting surround",
          "Speaker setting surround back",
          "Zone 3 amplifier",
          "Speaker setting presence",
          "Bass out",
          "Subwoofer phase",
          "Subwoofer phase",
          "Test mode",
          "EQ select",
          "Wallpaper",
          "N/A",
          "N/A",
          "N/A",
          "HDMI audio output",
          "Component I/P",
          "HDMI IP",
          "GUI language",
          "HDMI upscaling",
          "HDMI aspect",
          "THX surround back speaker distance",
          "Zone OSD",
          "Decoder select",
          "Remote ID tuner",
          "Advanced setup",
          "Remote ID amplifier",
          "Fan control mode",
          "Speaker impedance",
          "Tuner setup",
          "Pure direct",
          "Zone 3 input",
          "Zone 3 mute",
          "Zone 3 volume",
          "Zone 3 volume",
          "Remote sensor",
          "Multi-channel select",
          "Remote ID XM",
          "Bi-amp",
          "Subwoofer crossover",
          "TV format",
          "Presence/surround back priority",
          "N/A",
          "Zone 2 tone control bass",
          "Zone 2 tone control bass",
          "Zone 2 tone control treble",
          "Zone 2 tone control treble",
          "Tone bypass",
          "Wake on RS-232 access",
          "Bit rate",
          "Bit rate",
          "Dialog",
          "Dialog",
          "FL scroll",
          "Multi-channel background video",
          "iPod charge on standby",
          "iPod repeat",
          "iPod shuffle",
          "NET/USB repeat",
          "NET/USB shuffle",
          "Zone 2 max volume",
          "Zone 2 initial volume",
          "Zone 2 initial volume",
          "Zone 2 balance",
          "Zone 2 balance",
          "Zone 3 max volume",
          "Zone 3 initial volume",
          "Zone 3 initial volume",
          "Zone 3 balance",
          "Zone 3 balance",
          "NET/USB source select",
          "Monitor check",
          "Zone 3 tone control bass",
          "Zone 3 tone control bass",
          "Zone 3 tone control treble",
          "Zone 3 tone control treble",
          "Flag",
          "Flag"]
      end
    end

    context 'RX-V2400' do
      let(:model_name) { 'RX-V2400/RX-Z9' }

      it 'returns correct fields' do
        executor.send(:build_fields, status_fields, model_id).should == [
          "Baud rate (@)",
          "Receive buffer (E)",
          "Receive buffer (0)",
          "Command timeout (1)",
          "Command timeout (9)",
          "Command timeout (0)",
          "Handshaking (0)",
          "System busy flag",
          "Power boolean",
          "Input",
          "Multi-channel input",
          "Input mode",
          "Mute",
          "Zone 2 input",
          "Zone 2 mute",
          "Master volume",
          "Master volume",
          "Zone 2 volume",
          "Zone 2 volume",
          "Program",
          "Program",
          "Effect",
          "Extended surround",
          "OSD short message",
          "Sleep timer",
          "Tuner preset page",
          "Tuner preset number",
          "Night mode",
          "N/A",
          "Speaker A relay",
          "Speaker B relay",
          "Playback",
          "Sampling",
          "EX/ES playback",
          "Thr / bypass",
          "RED DTS",
          "Headphones",
          "Tuner band",
          "Tuner tuned",
          "Trigger 1 output",
          "N/A",
          "N/A",
          "Trigger 1 control",
          "DTS 96/24",
          "Trigger 2 control",
          "Trigger 2 output",
          "Speaker B setting",
          "Zone 2 amplifier",
          "Level main right",
          "Level main right",
          "Level main left",
          "Level main left",
          "Level center",
          "Level center",
          "Level rear right",
          "Level rear right",
          "Level rear left",
          "Level rear left",
          "Level surround back right",
          "Level surround back right",
          "Level surround back left",
          "Level surround back left",
          "Level front effect right",
          "Level front effect right",
          "Level front effect left",
          "Level front effect left",
          "Level subwoofer",
          "Level subwoofer",
          "N/A",
          "N/A",
          "N/A",
          "N/A",
          "N/A",
          "N/A",
          "LFE level speakers",
          "LFE level speakers",
          "LFE level headphones",
          "LFE level headphones",
          "Audio delay",
          "Audio delay",
          "N/A",
          "N/A",
          "N/A",
          "N/A",
          "Audio select setting",
          "Dimmer",
          "OSD Message",
          "OSD shift",
          "OSD shift",
          "Gray back",
          "Video conversion",
          "Dynamic range speakers",
          "Dynamic range headphones",
          "Zone 2 volume out",
          "N/A",
          "Memory guard",
          "Speaker setting center",
          "Speaker setting main",
          "Speaker setting rear",
          "Speaker setting surround back",
          "Speaker setting front effect",
          "Bass out",
          "Multi-channel center out",
          "Multi-channel subwoofer out",
          "Main level",
          "Test mode",
          "N/A",
          "Multi-channel level main left",
          "Multi-channel level main left",
          "Multi-channel level main right",
          "Multi-channel level main right",
          "Multi-channel level center",
          "Multi-channel level center",
          "Multi-channel level rear left",
          "Multi-channel level rear left",
          "Multi-channel level rear right",
          "Multi-channel level rear right",
          "Multi-channel level surround back left",
          "Multi-channel level surround back left",
          "Multi-channel level surround back right",
          "Multi-channel level surround back right",
          "Multi-channel level front effect left",
          "Multi-channel level front effect left",
          "Multi-channel level front effect right",
          "Multi-channel level front effect right",
          "Multi-channel level subwoofer",
          "Multi-channel level subwoofer",
          "Zone 3 input",
          "Zone 3 mute",
          "Zone 3 volume",
          "Zone 3 volume",
          "N/A",
          "Multi-channel select",
          "Multi-channel surround out",
          "Speaker setting subwoofer",
          "Subwoofer crossover",
          "Component OSD",
          "Presence/surround back priority"]
      end
    end
  end
end
