# frozen_string_literal: true

module Seriamp
  module Yamaha
    module Protocol
      module GetConstants

        private

        STATUS_HEAD_FIELDS = [
          'DC2',
          'Model',
          'Model',
          'Model',
          'Model',
          'Model',
          'FW Version',
          'Data length',
          'Data length',
        ]

        STATUS_FIELDS = [
          'Baud rate (@)',
          'Receive buffer (E)',
          'Receive buffer (0)',
          'Command timeout (1)',
          'Command timeout (9)',
          'Command timeout (0)',
          'Handshaking (0)',
          'System busy flag',
          'Power boolean',
          'Input',
          'Multi-channel input',
          'Input mode',
          'Mute',
          'Zone 2 input',
          'Zone 2 mute',
          'Master volume',
          'Master volume',
          'Zone 2 volume',
          'Zone 2 volume',
          'Program',
          'Program',
          'Effect',
          'Extended surround',
          'OSD short message',
          'Sleep timer',
          'Tuner preset page',
          'Tuner preset number',
          'Night mode',
          # DT28
          [:>=, 'R0210', 'Night mode parameter'],
          [:<, 'R0210', 'N/A'],
          'Speaker A relay',
          'Speaker B relay',
          # DT31
          [:>=, 'R0210', 'Format'],
          [:>=, 'R0210', 'Format'],
          [:>=, 'R0210', 'Sampling'],
          [:>=, 'R0210', 'Sampling'],
          [:>=, 'R0210', 'Channels front/rear'],
          [:<, 'R0210', 'Playback'],
          [:<, 'R0210', 'Sampling'],
          [:<, 'R0210', 'EX/ES playback'],
          [:<, 'R0210', 'Thr / bypass'],
          [:<, 'R0210', 'RED DTS'],
          # DT36
          'Headphones',
          'Tuner band',
          # DT38
          [:>=, 'R0210', 'Channel LFE'],
          [:<, 'R0210', 'Tuner tuned'],
          'Trigger 1 output',
          # DT40
          [:>=, 'R0210', 'Decoder mode'],
          [:<, 'R0210', 'N/A'],
          # DT41
          [:>=, 'R0210', 'Dual mono'],
          [:<, 'R0210', 'N/A'],
          'Trigger 1 control',
          # DT43
          [:>=, 'R0210', 'N/A'],
          [:<, 'R0210', 'DTS 96/24'],
          'Trigger 2 control',
          'Trigger 2 output',
          'Speaker B setting',
          'Zone 2 amplifier',
          [:>, 'R0161', 'Level front right'],
          [:<=, 'R0161', 'Level main right'],
          [:>, 'R0161', 'Level front right'],
          [:<=, 'R0161', 'Level main right'],
          [:>, 'R0161', 'Level front left'],
          [:<=, 'R0161', 'Level main left'],
          [:>, 'R0161', 'Level front left'],
          [:<=, 'R0161', 'Level main left'],
          'Level center',
          'Level center',
          [:>, 'R0161', 'Level surround right'],
          [:<=, 'R0161', 'Level rear right'],
          [:>, 'R0161', 'Level surround right'],
          [:<=, 'R0161', 'Level rear right'],
          [:>, 'R0161', 'Level surround left'],
          [:<=, 'R0161', 'Level rear left'],
          [:>, 'R0161', 'Level surround left'],
          [:<=, 'R0161', 'Level rear left'],
          'Level surround back right',
          'Level surround back right',
          'Level surround back left',
          'Level surround back left',
          [:>, 'R0161', 'Level presence right'],
          [:<=, 'R0161', 'Level front effect right'],
          [:>, 'R0161', 'Level presence right'],
          [:<=, 'R0161', 'Level front effect right'],
          [:>, 'R0161', 'Level presence left'],
          [:<=, 'R0161', 'Level front effect left'],
          [:>, 'R0161', 'Level presence left'],
          [:<=, 'R0161', 'Level front effect left'],
          'Level subwoofer',
          'Level subwoofer',
          # DT68
          [:>=, 'R0210', 'XM preset page'],
          [:>=, 'R0210', 'XM preset number'],
          [:>=, 'R0210', 'XM search mode'],
          [:>=, 'R0210', 'On screen OSD'],
          [:>=, 'R0210', 'XM channel number'],
          [:>=, 'R0210', 'XM channel number'],
          [:<, 'R0210', 'N/A'],
          [:<, 'R0210', 'N/A'],
          [:<, 'R0210', 'N/A'],
          [:<, 'R0210', 'N/A'],
          [:<, 'R0210', 'N/A'],
          [:<, 'R0210', 'N/A'],
          # DT74
          'LFE level speakers',
          'LFE level speakers',
          'LFE level headphones',
          'LFE level headphones',
          'Audio delay',
          'Audio delay',
          # DT80
          [:>=, 'R0210', 'Initial volume'],
          [:>=, 'R0210', 'Initial volume'],
          [:>=, 'R0210', 'Max volume'],
          [:>=, 'R0210', 'Decoder mode setting'],
          [:<, 'R0210', 'N/A'],
          [:<, 'R0210', 'N/A'],
          [:<, 'R0210', 'N/A'],
          [:<, 'R0210', 'N/A'],
          # DT84
          'Audio select setting',
          'Dimmer',
          [:>, 'R0161', 'N/A'],
          [:<=, 'R0161', 'OSD Message'],
          'OSD shift',
          'OSD shift',
          'Gray back',
          'Video conversion',
          'Dynamic range speakers',
          'Dynamic range headphones',
          'Zone 2 volume out',
          [:>, 'R0161', 'Zone 3 volume out'],
          [:<=, 'R0161', 'N/A'],
          'Memory guard',
          'Speaker setting center',
          # DT97
          [:>, 'R0161', 'Speaker setting front'],
          [:>, 'R0161', 'Speaker setting surround'],
          [:>, 'R0161', 'Speaker setting surround back'],
          [:>, 'R0161', 'Zone 3 amplifier'],
          [:>, 'R0161', 'Speaker setting presence'],
          [:>, 'R0161', 'Bass out'],
          [:>, 'R0161', 'Subwoofer phase'],
          [:>, 'R0161', 'Subwoofer phase'],
          [:<=, 'R0161', 'Speaker setting main'],
          [:<=, 'R0161', 'Speaker setting rear'],
          [:<=, 'R0161', 'Speaker setting surround back'],
          [:<=, 'R0161', 'Speaker setting front effect'],
          [:<=, 'R0161', 'Bass out'],
          [:<=, 'R0161', 'Multi-channel center out'],
          [:<=, 'R0161', 'Multi-channel subwoofer out'],
          [:<=, 'R0161', 'Main level'],
          # DT105
          'Test mode',
          [:>=, 'R0210', 'EQ select'],
          [:<, 'R0210', 'N/A'],
          # DT107
          [:>=, 'R0210', 'Wallpaper'],
          [:>=, 'R0210', 'N/A'],
          [:>=, 'R0210', 'N/A'],
          [:>=, 'R0210', 'N/A'],
          [:>=, 'R0210', 'HDMI audio output'],
          [:>=, 'R0210', 'Component I/P'],
          [:>=, 'R0210', 'HDMI IP'],
          [:>=, 'R0210', 'GUI language'],
          [:>=, 'R0210', 'HDMI upscaling'],
          [:>=, 'R0210', 'HDMI aspect'],
          [:>=, 'R0210', 'THX surround back speaker distance'],
          [:>=, 'R0210', 'Zone OSD'],
          [:>=, 'R0210', 'Decoder select'],
          [:>=, 'R0210', 'Remote ID tuner'],
          [:>=, 'R0210', 'Advanced setup'],
          [:>=, 'R0210', 'Remote ID amplifier'],
          [:>=, 'R0210', 'Fan control mode'],
          [:>=, 'R0210', 'Speaker impedance'],
          [:>=, 'R0210', 'Tuner setup'],
          [:>=, 'R0210', 'Pure direct'],
          [:>=, 'R0210', 'Zone 3 input'],
          [:>=, 'R0210', 'Zone 3 mute'],
          [:>=, 'R0210', 'Zone 3 volume'],
          [:>=, 'R0210', 'Zone 3 volume'],
          [:>=, 'R0210', 'Remote sensor'],
          [:<, 'R0210', 'Multi-channel level main left'],
          [:<, 'R0210', 'Multi-channel level main left'],
          [:<, 'R0210', 'Multi-channel level main right'],
          [:<, 'R0210', 'Multi-channel level main right'],
          [:<, 'R0210', 'Multi-channel level center'],
          [:<, 'R0210', 'Multi-channel level center'],
          [:<, 'R0210', 'Multi-channel level rear left'],
          [:<, 'R0210', 'Multi-channel level rear left'],
          [:<, 'R0210', 'Multi-channel level rear right'],
          [:<, 'R0210', 'Multi-channel level rear right'],
          [:<, 'R0210', 'Multi-channel level surround back left'],
          [:<, 'R0210', 'Multi-channel level surround back left'],
          [:<, 'R0210', 'Multi-channel level surround back right'],
          [:<, 'R0210', 'Multi-channel level surround back right'],
          [:<, 'R0210', 'Multi-channel level front effect left'],
          [:<, 'R0210', 'Multi-channel level front effect left'],
          [:<, 'R0210', 'Multi-channel level front effect right'],
          [:<, 'R0210', 'Multi-channel level front effect right'],
          [:<, 'R0210', 'Multi-channel level subwoofer'],
          [:<, 'R0210', 'Multi-channel level subwoofer'],
          [:<, 'R0210', 'Zone 3 input'],
          [:<, 'R0210', 'Zone 3 mute'],
          [:<, 'R0210', 'Zone 3 volume'],
          [:<, 'R0210', 'Zone 3 volume'],
          [:<, 'R0210', 'N/A'],
          # DT132
          'Multi-channel select',
          # DT133
          [:>=, 'R0210', 'Remote ID XM'],
          [:>=, 'R0210', 'Bi-amp'],
          [:<, 'R0210', 'Multi-channel surround out'],
          [:<, 'R0210', 'Speaker setting subwoofer'],
          # DT135
          'Subwoofer crossover',
          # DT136
          [:>=, 'R0210', 'TV format'],
          [:<, 'R0210', 'Component OSD'],
          # DT137
          'Presence/surround back priority',
          # RX-V2400 ends here
          [:<=, 'R0161', nil],
          'N/A',
          'Zone 2 tone control bass',
          'Zone 2 tone control bass',
          'Zone 2 tone control treble',
          'Zone 2 tone control treble',
          'Tone bypass',
          'Wake on RS-232 access',
          'Bit rate',
          'Bit rate',
          'Dialog',
          'Dialog',
          'FL scroll',
          'Multi-channel background video',
          'iPod charge on standby',
          'iPod repeat',
          'iPod shuffle',
          'NET/USB repeat',
          'NET/USB shuffle',
          'Zone 2 max volume',
          'Zone 2 initial volume',
          'Zone 2 initial volume',
          'Zone 2 balance',
          'Zone 2 balance',
          'Zone 3 max volume',
          'Zone 3 initial volume',
          'Zone 3 initial volume',
          'Zone 3 balance',
          'Zone 3 balance',
          'NET/USB source select',
          'Monitor check',
          'Zone 3 tone control bass',
          'Zone 3 tone control bass',
          'Zone 3 tone control treble',
          'Zone 3 tone control treble',
          'Flag',
          'Flag',
        ]

        STATUS_TAIL_FIELDS = [
          'Checksum',
          'Checksum',
          'ETX',
        ]

        MAIN_INPUTS_GET = {
          '0' => 'PHONO',
          '1' => 'CD',
          '2' => 'TUNER',
          '3' => 'CD-R',
          '4' => 'MD/TAPE',
          '5' => 'DVD',
          '6' => 'DTV',
          '7' => 'CBL/SAT',
          '8' => 'SAT',
          '9' => 'VCR1',
          'A' => 'DVR/VCR2',
          'B' => 'VCR3/DVR',
          'C' => 'V-AUX/DOCK',
          'D' => 'NET/USB',
          'E' => 'XM',
        }.freeze

        DECODER_MODE_GET = {
          '0' => 'Auto',
          '1' => 'DTS',
          '2' => 'AAC',
        }.freeze

        AUDIO_SELECT_GET = {
          '0' => 'Auto', # Confirmed RX-V1500
          '2' => 'DTS', # Confirmed RX-V1500
          '3' => 'Coax / Opt', # Unconfirmed
          '4' => 'Analog', # Confirmed RX-V1500
          '5' => 'Analog Only', # Unconfirmed
          '8' => 'HDMI', # Unconfirmed
        }.freeze

        NIGHT_GET = {
          '0' => 'Off',
          '1' => 'Cinema',
          '2' => 'Music',
        }.freeze

        SLEEP_GET = {
          '0' => 120,
          '1' => 90,
          '2' => 60,
          '3' => 30,
          '4' => nil,
        }.freeze

        PROGRAM_GET = {
          '00' => 'Munich',
          '01' => 'Hall B',
          '02' => 'Hall C',
          '04' => 'Hall D',
          '05' => 'Vienna',
          '06' => 'Live Concert',
          '07' => 'Hall in Amsterdam',
          '08' => 'Tokyo',
          '09' => 'Freiburg',
          '0A' => 'Royaumont',
          '0B' => 'Chamber',
          '0C' => 'Village Gate',
          '0D' => 'Village Vanguard',
          '0E' => 'The Bottom Line',
          '0F' => 'Cellar Club',
          '10' => 'The Roxy Theater',
          '11' => 'Warehouse Loft',
          '12' => 'Arena',
          '14' => 'Disco',
          '15' => 'Party',
          '17' => '7ch Stereo',
          '18' => 'Music Video',
          '19' => 'DJ',
          '1C' => 'Recital/Opera',
          '1D' => 'Pavilion',
          '1E' => 'Action Gamae',
          '1F' => 'Role Playing Game',
          '20' => 'Mono Movie',
          '21' => 'Sports',
          '24' => 'Spectacle',
          '25' => 'Sci-Fi',
          '28' => 'Adventure',
          '29' => 'Drama',
          '2C' => 'Surround Decode',
          '2D' => 'Standard',
          '30' => 'PLII Movie',
          '31' => 'PLII Music',
          '32' => 'Neo:6 Movie',
          '33' => 'Neo:6 Music',
          '34' => '2ch Stereo',
          '35' => 'Direct Stereo',
          '36' => 'THX Cinema',
          '37' => 'THX Music',
          '3C' => 'THX Game',
          '40' => 'Enhancer 2ch Low',
          '41' => 'Enhancer 2ch High',
          '42' => 'Enhancer 7ch Low',
          '43' => 'Enhancer 7ch High',
          '80' => 'Straight',
        }.freeze

        FORMAT_GET = {
          '00' => 'Analog',
          '01' => 'PCM',
          '02' => 'DSD',
          '03' => 'Digital',
          '04' => 'Dolby Digital',
          '05' => 'DTS',
          '06' => 'AAC',
          '07' => 'DTS-HD',
          '08' => 'DTS-HD MSTR',
          '09' => 'DD Plus',
          '0A' => 'TrueHD',
          '0B' => 'WMA',
          '0C' => 'MP3',
          'FE' => '???',
          'FF' => '---',
        }.freeze

        SAMPLING_GET = {
          '00' => 'Analog',
          '01' => '8000',
          '02' => '11025',
          '03' => '12000',
          '04' => '16000',
          '05' => '22050',
          '06' => '24000',
          '07' => '32000',
          '08' => '44100',
          '09' => '48000',
          '0A' => '64000',
          '0B' => '88200',
          '0C' => '96000',
          '0D' => '128000',
          '0E' => '176400',
          'OF' => '192000',
          '10' => 'DSD', # 2.8224 MHz
          'FE' => '???',
          'FF' => '---',
        }.freeze

        INPUT_CHANNELS_GET = {
          '00' => '1+',
          '01' => '1/0',
          '02' => '2/0',
          '03' => '3/0',
          '04' => '2/1',
          '05' => '3/1',
          '06' => '2/2',
          '07' => '3/2',
          '08' => '2/3',
          '09' => '3/3',
          '0A' => '2/4',
          '0B' => '3/4',
          'AC' => 'MLT',
          '0F' => '---',
        }.freeze

        INPUT_LFE_CHANNEL_GET = {
          '00' => '0.1',
          'FF' => '---',
        }.freeze

        BIT_RATE_GET = {
          '00' => '32000',
          '01' => '40000',
          '02' => '48000',
          '03' => '56000',
          '04' => '64000',
          '05' => '72000',
          '06' => '80000',
          '07' => '96000',
          '08' => '112000',
          '09' => '128000',
          '0A' => '144000',
          '0B' => '160000',
          '0C' => '192000',
          '0D' => '224000',
          '0E' => '256000',
          '0F' => '288000',
          '10' => '320000',
          '11' => '384000',
          '12' => '448000',
          '13' => '512000',
          '14' => '576000',
          '15' => '640000',
          '16' => '768000',
          '17' => '960000',
          '18' => '1024000',
          '19' => '1152000',
          '1A' => '1280000',
          '1B' => '1344000',
          '1C' => '1408000',
          '1D' => '1411200',
          '1E' => '1472000',
          '1F' => '1536000',
          '20' => '1920000',
          '21' => '2048000',
          '22' => '3072000',
          '23' => '3840000',
          '24' => 'Open',
          '25' => 'Variable',
          '26' => 'Losless',
          'FF' => '---',
        }.freeze

        POWER_GET = {
          '00' => {main_power: false, zone2_power: false, zone3_power: false}.freeze,
          '01' => {main_power: true, zone2_power: true, zone3_power: true}.freeze,
          '02' => {main_power: true, zone2_power: false, zone3_power: false}.freeze,
          '03' => {main_power: false, zone2_power: true, zone3_power: true}.freeze,
          '04' => {main_power: true, zone2_power: true, zone3_power: false}.freeze,
          '05' => {main_power: true, zone2_power: false, zone3_power: false}.freeze,
          '06' => {main_power: false, zone2_power: true, zone3_power: true}.freeze,
          '07' => {main_power: false, zone2_power: false, zone3_power: true}.freeze,
        }.freeze

        INPUT_NAME_GET = {
          '00' => 'PHONO',
          '01' => 'CD',
          '02' => 'TUNER',
          '03' => 'CD-R',
          '04' => 'MD/TAPE',
          '05' => 'DVD',
          '06' => 'DTV',
          '07' => 'CBL/SAT',
          '08' => 'SAT',
          '09' => 'VCR1',
          '0A' => 'DVR/VCR2',
          '0B' => 'VCR3/DVR',
          '0C' => 'V-AUX/DOCK',
          '0D' => 'NET/USB',
          '0E' => 'XM',
          '10' => 'Multi-Channel',
        }.freeze

        MUTE_GET = {
          '00' => false,
          '01' => true,
        }.freeze

        XM_MESSAGE_GET = {
          '00' => 'Check Antenna',
          '01' => 'Updating',
          '02' => 'No Signal',
          '03' => 'Loading',
          '04' => 'Off Air',
          '05' => 'Unavailable',
        }.freeze

        SPEAKER_A_GET = {
          '00' => false,
          '01' => true,
        }.freeze

        SPEAKER_B_GET = SPEAKER_A_GET

        TEST_GET = SPEAKER_A_GET

        GET_MAP = {
          '06' => :xm_message,
          '10' => :format,
          '11' => :sampling,
          '12' => :input_channels,
          '13' => :input_lfe_channel,
          '14' => :bit_rate,
          '20' => :power,
          '21' => :input_name,
          '23' => :mute,
          '28' => :program,
          '2E' => :speaker_a,
          '2F' => :speaker_b,
          # Speaker level test mode
          '80' => :test,
        }.freeze
      end
    end
  end
end
