# frozen_string_literal: true

module Seriamp
  module Yamaha
    module Protocol
      module Status

        private

        STATUS_FIELDS = {
          'R0178' => [
            [7],
            [:busy, :bool],
            [:power, :bool],
            [:input_name, :input_name_1],
            [:multi_ch_input, :bool],
            [:input_mode],
            [:mute, :bool],
            [:zone2_input_name, :input_name_1],
            [:zone2_mute, :bool],
            [2, :main_volume, :half_db_volume],
            [2, :zone2_volume, :half_db_volume],
            [2, :program_name],
            [:effect, :bool],
            [:es_key],
            [:osd],
            [:sleep],
            [:tuner_page],
            [:tuner_number],
            [:night],
            [:pure_direct, :bool],
            [:speaker_a, :bool],
            [:speaker_b, :bool],
            [:playback_mode],
            [:sample_rate, :sample_rate_1],
            [:es_status],
            [:thr_bypass, :bool],
            [:red_dts_wait, :bool],
            [:headphone, :bool],
            [:tuner_band],
            [:tuned, :bool],
            [:trigger1, :bool],
            [2],
            [:trigger1_control, :trigger_control],
            [:dts_96_24, :bool],
            [:trigger2_control, :trigger_control],
            [:trigger2, :bool],
            [:speaker_b_zone],
            [:zone2_speaker, :bool],
            [2, :front_right_level, :speaker_level],
            [2, :front_left_level, :speaker_level],
            [2, :center_level, :speaker_level],
            [2, :surround_right_level, :speaker_level],
            [2, :surround_left_level, :speaker_level],
            [2, :surround_back_right_level, :speaker_level],
            [2, :surround_back_left_level, :speaker_level],
            [2, :presence_right_level, :speaker_level],
            [2, :presence_left_level, :speaker_level],
            [2, :subwoofer_level, :speaker_level],
            [:night_mode],
            [5],
            [2, :speaker_lfe_level, :speaker_level],
            [2, :headphone_lfe_level, :speaker_level],
            [2, :audio_delay],
            [4],
            [:input_mode_setting],
            [:dimmer],
            [:osd_message],
            [2, :osd_shift],
            [:gray_back, :bool],
            [:video_conversion, :bool],
            [:speaker_dynamic_range, :dynamic_range],
            [:headphone_dynamic_range, :dynamic_range],
            [:zone2_volume_out, :volume_out],
            [1],
            [:memory_guard, :bool],
            [:center_speaker_setting, :speaker_setting],
            [:front_speaker_setting, :speaker_setting],
            [:surround_speaker_setting, :speaker_setting],
            [:surround_back_speaker_setting, :speaker_setting],
            [:presence_speaker_setting, :inverted_bool],
            [:bass_out],
            [:multi_ch_center_out],
            [:multi_ch_subwoofer_out],
            [:main_level],
            [:test_mode],
            [1],
            [2, :multi_ch_front_left_level, :speaker_level],
            [2, :multi_ch_front_right_level, :speaker_level],
            [2, :multi_ch_center_level, :speaker_level],
            [2, :multi_ch_surround_left_level, :speaker_level],
            [2, :multi_ch_surround_right_level, :speaker_level],
            [2, :multi_ch_surround_back_left_level, :speaker_level],
            [2, :multi_ch_surround_back_right_level, :speaker_level],
            [2, :multi_ch_presence_left_level, :speaker_level],
            [2, :multi_ch_presence_right_level, :speaker_level],
            [2, :multi_ch_subwoofer_level, :speaker_level],
            [:zone3_input_name, :input_name_1],
            [:zone3_mute, :bool],
            [2, :zone3_volume, :half_db_volume],
            [1],
            [:multi_ch_select],
            [:multi_ch_surround_out],
            [:subwoofer_position],
            [:subwoofer_crossover],
            [:component_osd, :bool],
            [:presence_surround_back_select],
          ].freeze,
          'R0212' => [
            [7],
            [:busy_standby],
            [:power],
            [2, :input_name, :input_name_2],
            [:audio_select],
            [:mute, :bool],
            [:zone2_input_name, :input_name_1],
            [:zone2_mute, :bool],
            [2, :main_volume, :half_db_volume],
            [2, :zone2_volume, :half_db_volume],
            [2, :program_name],
            [1],
            [:es_key],
            [:osd_message],
            [:sleep],
            [:tuner_page],
            [:tuner_number],
            [:night_mode],
            [:night_mode_parameter],
            [2],
            [2, :format],
            [2, :sample_rate, :sample_rate_2],
            [:channel_indicator],
            [:headphone, :bool],
            [:tuner_band],
            [:lfe_indicator],
            [:trigger1, :bool],
            [:decoder_mode],
            [:dual_mono_out],
            [:trigger1_control, :trigger_control],
            [1],
            [:trigger2_control, :trigger_control],
            [:trigger2, :bool],
            [1],
            [:zone2_speaker_out, :speaker_out],
            [2, :front_right_level, :speaker_level],
            [2, :front_left_level, :speaker_level],
            [2, :center_level, :speaker_level],
            [2, :surround_right_level, :speaker_level],
            [2, :surround_left_level, :speaker_level],
            [2, :surround_back_right_level, :speaker_level],
            [2, :surround_back_left_level, :speaker_level],
            [2, :presence_right_level, :speaker_level],
            [2, :presence_left_level, :speaker_level],
            [2, :subwoofer_level, :speaker_level],
            [:xm_preset_page, :tuner_page],
            [:xm_preset_number, :tuner_number],
            [:xm_search_mode],
            [:on_screen],
            [2, :xm_channel_number],
            [2, :speaker_lfe_level, :speaker_level],
            [2, :headphone_lfe_level, :speaker_level],
            [2, :audio_delay],
            [2, :initial_volume, :half_db_volume], # RX-V2700 only
            [:max_volume], # RX-V2700 only
            [:decoder_mode_setting],
            [:audio_select_setting],
            [:dimmer],
            [1],
            # [2, :osd_shift], # RX-V1700
            [2, :gui_position], # RX-V2700
            [:gray_back, :bool],
            [:video_conversion, :bool],
            [:speaker_dynamic_range, :dynamic_range],
            [:headphone_dynamic_range, :dynamic_range],
            [:zone2_volume_out, :volume_out],
            [:zone3_volume_out, :volume_out],
            [:memory_guard, :bool],
            [:center_speaker_setting, :speaker_setting],
            [:front_speaker_setting, :speaker_setting],
            [:surround_speaker_setting, :speaker_setting],
            [:surround_back_speaker_setting, :sb_speaker_setting],
            [:zone3_speaker_out, :speaker_out],
            [:presence_speaker_setting, :inverted_bool],
            [:bass_out],
            [:subwoofer_phase],
            [1],
            [:test_mode, :bool],
            [:eq_select], # RX-V1700 only
            [:wallpaper], # RX-V2700 only
            [3],
            [:hdmi_audio, :inverted_bool],
            [:component_ip, :bool],
            [:hdmi_ip, :bool], # RX-V1700 only
            [:gui_language], # RX-V2700 only
            [:hdmi_upscaling],
            [:hdmi_aspect],
            [1],
            [:zone_osd], # RX-V2700 only
            [:decoder_select],
            [:tuner_remote_id, :remote_id],
            [:advanced_setup, :bool],
            [:amp_remote_id, :remote_id],
            [1],
            [:speaker_impedance],
            [:tuner_setup],
            [:pure_direct, :bool],
            [:zone3_input_name, :input_name_1],
            [:zone3_mute, :bool],
            [2, :zone3_volume, :half_db_volume],
            [:remote_sensor, :bool],
            [:multi_ch_select],
            [:remote_id_xm],
            [:biamp, :inverted_bool],
            [:subwoofer_crossover],
            [:tv_format], # RX-V2700
            [:presence_surround_back_select],
            [1],
            [2, :zone2_bass, :zone_tone],
            [2, :zone2_treble, :zone_tone],
            [:tone_bypass, :inverted_bool],
            [:wake_on_rs232, :bool],
            [2, :bit_rate],
            [2, :dialog_level],
            [:fl_scroll],
            [:multi_ch_bgv],
            [:ipod_charge_standby, :bool],
            [:ipod_repeat],
            [:ipod_shuffle],
            [:net_usb_repeat], # RX-V2700 only
            [:net_usb_shuffle, :bool], # RX-V2700 only
            [:zone2_max_volume, :max_volume], # RX-V2700 only
            [2, :zone2_initial_volume, :half_db_volume], # RX-V2700 only
            [2, :zone2_balance, :balance],
            [:zone3_max_volume, :max_volume], # RX-V2700 only
            [2, :zone3_initial_volume, :half_db_volume], # RX-V2700 only
            [2, :zone3_balance, :balance],
            [:net_usb_source], # RX-V2700 only
            [:monitor_check, :bool],
            [2, :zone3_bass, :zone_tone],
            [2, :zone3_treble, :zone_tone],
            [2, :flag],
          ].freeze,
        }.freeze

        STATUS_FIELDS_R0178 = [
          [nil, nil, 'Baud rate (@)'],
          [nil, nil, 'Receive buffer (E)'],
          [nil, nil, 'Receive buffer (0)'],
          [nil, nil, 'Command timeout (1)'],
          [nil, nil, 'Command timeout (9)'],
          [nil, nil, 'Command timeout (0)'],
          [nil, nil, 'Handshaking (0)'],

          [:busy, :off_on, 'System busy status'],
          [:power, :off_on, 'System power'],
          [:input, nil, 'Main zone input'],
          [:multi_ch_input, :off_on, 'Input is multi-channel input'],
          [:input_mode, nil, 'Input mode'],
          [:mute, :off_on, 'Main zone mute'],
        ].freeze

        STATUS_FIELDS_R0226 = (STATUS_FIELDS_R0178[..6] + [
        ]).freeze

        STATUS_FIELDS_MAP = {
          'R0178' => STATUS_FIELDS_R0178,
          'R0226' => STATUS_FIELDS_R0226,
        }.freeze
      end
    end
  end
end
